apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 1m
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress
      version: '0.14.x'
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      interval: 1m
  targetNamespace: nginx-ingress-controller
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 3
      service:
        type: NodePort
        httpPort:
          nodePort: 8080
        httpsPort:
          nodePort: 4443