apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx-ingress
      version: '2.x.x'
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: nginx-ingress-controller
      interval: 1m
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 2